# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended', '0002_tweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.TextField(max_length=280),
        ),
    ]
