# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended', '0003_auto_20181028_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follower',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='follows',
            name='following',
            field=models.TextField(),
        ),
    ]
