# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended', '0004_auto_20181028_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='userId',
        ),
        migrations.AddField(
            model_name='tweets',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
